apiVersion: v1
kind: Pod
metadata:
  name: redis-master
spec:
  containers:
  - name: redis-master
    image: redis
    ports:
    - containerPort: 6379

---
apiVersion: v1
kind: Pod
metadata:
  name: redis-slave
spec:
  containers:
  - name: redis-slave
    image: redis
    ports:
    - containerPort: 6379
    command: ["sh", "-c", "redis-server --slaveof $$REDIS_MASTER_HOST 6379"]
    env:
    - name: redis-master
      valueFrom:
        configMapKeyRef:
          name: redis-variables
          key: REDIS_MASTER_HOST